using FluentValidation.Results;

namespace PurpleRock.Application.Common.Exceptions;

/// <summary>
/// Validation exception class.
/// </summary>
public class ValidationException : Exception
{
  /// <summary>
  /// Initializes a new instance of the <see cref="ValidationException"/> class.
  /// </summary>
  public ValidationException()
      : base("One or more validation failures have occurred.")
  {
    Errors = new Dictionary<string, string[]>();
  }

  /// <summary>
  /// Initializes a new instance of the <see cref="ValidationException"/> class.
  /// </summary>
  /// <param name="failures">The failed properties. </param>
  public ValidationException(IEnumerable<ValidationFailure> failures)
      : this()
  {
    Errors = failures
        .GroupBy(e => e.PropertyName, e => e.ErrorMessage)
        .ToDictionary(failureGroup => failureGroup.Key, failureGroup => failureGroup.ToArray());
  }

  /// <summary>
  /// Dictionary of validation errors.
  /// </summary>
  public IDictionary<string, string[]> Errors { get; }
}
